#!/bin/bash

set -ex

if [[ ! -d /wiki/data ]]
then
  mv /opt/dokuwiki/data /wiki
fi

if [[ ! -d /wiki/conf ]]
then
  mv /opt/dokuwiki/conf /wiki

  ADMIN_PASSWORD_HASH=$(php5 -r "echo password_hash('${INITIAL_ADMIN_PASSWORD}', PASSWORD_BCRYPT);")
  sed -i -e "s/<SERVER_HOSTNAME>/${SERVER_HOSTNAME}/g" /wiki/conf/local.php
  sed -i -e "s@<ADMIN_PASSWORD_HASH>@${ADMIN_PASSWORD_HASH}@" /wiki/conf/users.auth.php
fi

chown www-data.www-data -R /wiki
rm -rf /opt/dokuwiki/conf
ln -s /wiki/conf /opt/dokuwiki/conf

if [[ -z $1 ]]
then
  exec php5-fpm --nodaemonize --force-stderr
else
  exec $@
fi

